### PR TITLE
Dev wilriker

### PR DESCRIPTION
**Pull request by chrishamm**

### CODE REVIEW

**Comment by chrishamm** [comment]
@wilriker @gtjoseph I think the gpio group name is too generic. IMO it would be better to call it dsf-io and to rename the rules file accordingly (SPI is no GPIO). In addition, the dsf/dsf-io groups + udev rules should be deleted when the package is removed.

Why don't you want to change the owner of /opt/dsf/sd to `dsf`? The files in there are probably owned by `root` so unless the permissions are changed, they will be no longer editable from DWC.

**Comment by gtjoseph** [comment]
> @wilriker @gtjoseph I think the gpio group name is too generic. IMO it would be better to call it dsf-io and to rename the rules file accordingly (SPI is no GPIO). In addition, the dsf/dsf-io groups + udev rules should be deleted when the package is removed.
> 

"gpio" and actually "spi" are existing groups in raspian.  No need to create another.  The "pi" user is already a member of both.

> Why don't you want to change the owner of /opt/dsf/sd to `dsf`? The files in there are probably owned by `root` so unless the permissions are changed, they will be no longer editable from DWC.

If the gcodes directory isn't writable by a user then it'll prevent users from uploading gcode files outside DWC.   That'll break slicer auto upload processes that many of us have today.  I'm fine with having a regular user added to the dsf group and having the directories group-writable.

**Comment by wilriker** [comment]
I would expect that `apt` removes the udev rules file a well as the system-sysusers/tmpfiles files. This would also remove the groups as they are created at runtime.
I can split the rules (GPIO/SPI) if you want but I took them from some other project exactly like this (don't remember which one, though). Also since they do not exclusively apply to DSF I rather hesitate to rename them to something having DSF/DCS in the name.

The directory permissions work as they are. The `/opt/dsd/sd`  directory being owned by `root` just means that no one can create our delete new top-level directories. The directories themselves as well as all files within being to `dsf` and there is no problem with add/edit/delete. I run my setup in this configuration for a while now.

**Comment by wilriker** [comment]
Latest commit addresses the first two points.

**Comment by wilriker** [comment]
Also fixed merge conflicts now.

**Comment by chrishamm** [comment]
Thanks, but please target the PR at v3.2-dev. The fix for the wrong CPU priority is already included there.

**Comment by wilriker** [comment]
There is no such branch but the `dev` branch I merged also had the CPU priority fix.

**Comment by chrishamm** [comment]
Sorry, my bad - I mixed that up with the DWC repo.

**Pull request merged**
